# Generated by Django 5.1.6 on 2025-02-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='head_goal',
        ),
    ]
