# Generated by Django 5.1.6 on 2025-02-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_goal_head_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='team_emblems/'),
        ),
    ]
