# Generated by Django 5.1.6 on 2025-02-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_emblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='acronym',
            field=models.CharField(max_length=3),
        ),
    ]
